### ISSUE TITLE
Create initial folder structure and routing

### ISSUE THREAD

**Issue by prachisg** [womenwhogo-yvr/symptom-tracker#1]
## Overview

We need to create an initial folder structure and basic routing to help the developers getting started to code on the project.

## Tasks

- [x] Update README.md (just a short description of the project)
- [x] Add .gitignore
- [x] Create initial skeleton folder structure
- [x] Setup basic routes `/` and `/symptoms`
- [x] Create handlers to handle the above routes
