### ISSUE TITLE
Create skeleton folder structure and basic routing

### ISSUE THREAD

**Issue by peachy19** [womenwhogo-yvr/symptom-tracker#1]
## Overview

We need to create a some initial setup to help the team getting started to code on the project.
This initial setup would include setting up the project structure and basic routing.

## Tasks
- [ ] Initialize a README.md
- [ ] Create skeleton folder structure
- [ ] Initialize routes - '/' and '/symptoms'
- [ ] Setup go handlers to handle the above routes
