### ISSUE TITLE
Feature: A user can add a daily entry

### ISSUE THREAD

**Issue by jesstice** [womenwhogo-yvr/symptom-tracker#5]
# Overview
This is the first screen a user will see once logged in. Users can:
- Add one or more symptoms
- Add notes

# Acceptance Criteria
- [ ] Screen is the first user sees when logged in
- [ ] Symptom field exists 
- [ ] User can add Symptom
- [ ] Number field exists with minus and plus symbols
- [ ] Clicking `+ Add Symptom` adds another symptom field with number field
- [ ] User can add notes to entry in paragraph text field

# User Experience 
Zepplin: https://app.zeplin.io/project/5bc8b8191311fc09c2449c2a/screen/5bc8b83d25d7094aac83beaf

![date - empty](https://user-images.githubusercontent.com/19242967/47323638-804b3280-d611-11e8-8860-2cb4e33a5595.png)

# Tasks
- [ ] Create `AddEntry` handler for any requests to `/entry/add`
- [ ] Create HTML template for form
